version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: 
      - web.env
    environment: 
      - ENVIRONMENT=production
      - SECRET_KEY=c3*pe4hs0ouhyebd@339*hm$$pef=1(7rd%cl#uwyv@-b=-6w))
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_LQSyKCkMqhn7gBUYlvCXDCFK000YjvkAbd
      - STRIPE_TEST_SECRET_KEY=sk_test_YjSOhFkXvKn0hn4wGhEnati000O8gVKwkc
      - DEBUG=0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
