version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - SECRET_KEY=c3*pe4hs0ouhyebd@339*hm$$pef=1(7rd%cl#uwyv@-b=-6w))
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: